In [1]:
import numpy as np

In [2]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [3]:
print(a[0])

[1 2 3 4]


In [4]:
a = np.array([1, 2, 3])

In [5]:
a

array([1, 2, 3])

In [6]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [8]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [10]:
# You can create an array with a range of elements

print(np.arange(4))
print(np.arange(0,10,3)) # (start, stop, step/kelipatan)

[0 1 2 3]
[0 3 6 9]


In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [14]:
np.delete(arr, 1) #hapusposisi 1

array([1, 3, 4, 5, 6, 7, 8])

In [15]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [16]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [18]:
array_example.ndim

3

In [19]:
array_example.size

24

In [20]:
array_example.shape

(3, 2, 4)

In [21]:
arr_one = np.array([[1, 2, 3, 4, 5]])

In [22]:
arr_one.ndim

2

In [23]:
arr_one.size

5

In [25]:
arr_one.shape

(1, 5)

In [26]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [34]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [35]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [36]:
# You can convert a 1D array to a row vector by inserting an axis along the first dimension

row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [37]:

col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [38]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [39]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [40]:

# You can add an axis at index position 0 with:

c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [41]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [42]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:

# You can easily print all of the values in the array that are less than 5

print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [44]:
five_up = (a >= 5)

print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [49]:
# You can select elements that are divisible by 2

divisible_by_2 = a[a%2==0]

print(divisible_by_2)

[ 2  4  6  8 10 12]


In [50]:

# you can select elements that satisfy two conditions using the & and | operators

c = a[(a > 2) & (a < 11)]

print(c)

[ 3  4  5  6  7  8  9 10]


In [51]:
arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [55]:
a_1 = np.array([[1, 1],
                [2, 2]])

In [56]:
a_2 = np.array([[3, 3],
                [4, 4]])

In [57]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [58]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [63]:
arrsplit = np.array([[1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
                     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [61]:
np.hsplit(arrsplit,4)

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8,  9],
        [19, 20, 21]]),
 array([[10, 11, 12],
        [22, 23, 24]])]

In [64]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:

# You can create a new array object that looks at the same data

b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [67]:

c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
a = np.array([1, 2, 3, 4])

# Add all of the elements in the array
a.sum()

10

In [69]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [70]:
b.sum(axis=0)

array([3, 3])

In [71]:

# You can sum the columns

b.sum(axis=1)

array([2, 4])

In [72]:
data = np.array([1, 2])
data

array([1, 2])

In [73]:
ones = np.ones(2)
ones

array([1., 1.])

In [74]:
data + ones

array([2., 3.])

In [77]:
data * data

array([1, 4])

In [78]:
data / data

array([1., 1.])

In [80]:
data.max()

2

In [81]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [82]:
A.sum()

4.8595784

In [83]:
A.min()

0.05093587

In [84]:
A.max()

0.82485143

In [88]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [89]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [92]:
A.std(0)

array([0.1794018 , 0.33973673, 0.05524104, 0.00759016])

In [93]:
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))

array([[0.45937284, 0.74031396],
       [0.27339197, 0.81328807],
       [0.83995249, 0.13134226]])

In [94]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.1489924  0.57252158]
 [0.55834006 0.28847495]
 [0.47855392 0.44987663]]


In [95]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [96]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [97]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [98]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [99]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


In [100]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [101]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [103]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


In [104]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [105]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [106]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [107]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [108]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [110]:
arr = np.arange(4).reshape((2, 2))
print(arr)

[[0 1]
 [2 3]]


In [111]:
ndarr = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [112]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [113]:
print(np.random.random((4,3,1)))

[[[0.22187099]
  [0.03110492]
  [0.4489908 ]]

 [[0.92100726]
  [0.25268622]
  [0.06163879]]

 [[0.63045633]
  [0.51247003]
  [0.42218651]]

 [[0.26858755]
  [0.05043017]
  [0.57946485]]]


In [114]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [115]:
# You can use flatten to flatten your array into a 1D array.

arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])