In [5]:
import numpy as np

In [21]:
data = np.array ([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 24, 26, 27])
print("#Input")
print("mulai: ", data[0])
print("Selesai: ", data.size)
print("")
print("#1 Dimensi")
data


#Input
mulai:  1
Selesai:  27

#1 Dimensi


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 24, 26, 27])

In [22]:
print("")
print("#2 Dimensi")
data.reshape(3,9)


#2 Dimensi


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 24, 26, 27]])

In [23]:
print("")
print("#3 Dimensi")
data.reshape(3,3,3)


#3 Dimensi


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [24, 26, 27]]])

In [24]:
#Soal 2

In [49]:
#input
n = int(input("Banyak data: "))
start = int (input("mulai: "))
end = int (input("Selesai: "))


Banyak data: 16
mulai: 1
Selesai: 50


In [52]:
data = np.random.randint(start, end, n)
data

array([ 3, 12, 38, 31, 26, 20,  4, 23, 46, 45, 25, 33, 26, 32, 27,  8])

In [54]:
#dua dimensi
duaDim = data.reshape(4,4)
duaDim

array([[ 3, 12, 38, 31],
       [26, 20,  4, 23],
       [46, 45, 25, 33],
       [26, 32, 27,  8]])

In [59]:
#tukarposisi
duaDim[:,::-1]

array([[31, 38, 12,  3],
       [23,  4, 20, 26],
       [33, 25, 45, 46],
       [ 8, 27, 32, 26]])

In [56]:
#soal 3

In [57]:
print("#Array 2 dimensi 10 x 10 ")
x = np.ones((10,10))*4
x[1:-1, 1:-1] = 0
x

#Array 2 dimensi 10 x 10 


array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])